# Generated by Django 2.0.2 on 2022-03-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='项目名称')),
                ('proj_owner', models.CharField(max_length=32, verbose_name='项目负责人')),
                ('test_owner', models.CharField(max_length=32, verbose_name='测试负责人')),
                ('dev_owner', models.CharField(max_length=32, verbose_name='开发负责人')),
                ('desc', models.TextField(max_length=120, verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='创建时间')),
            ],
        ),
    ]
